server:
  port: 8762
spring:
  application:
    name: eureka-web
  thymeleaf:
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
