server:
  port: 80
spring:
  application:
    name: web-demo
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/
  instance:
    prefer-ip-address: true
    instance-id: eureka-client:::${spring.cloud.client.ip-address}:${server.port}