server:
  port: 8763
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    registerWithEureka: true
    #是否从EurekaServer抓取注册信息,默认为true，集群必须设置才能配合ribbon使用负载均衡
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8763/eureka
spring:
  application:
    name: eureka-server