server:
  port: @eureka-server.port@
eureka:
  instance:
    hostname: @eureka-server.address@
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka-server